# Generated by Django 5.2.12 on 2026-04-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0002_remove_clearanceapproval_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceapproval',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
