# Generated by Django 5.2.12 on 2026-04-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0003_alter_clearanceapproval_approval_status'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clearanceapproval',
            unique_together={('request', 'department')},
        ),
    ]
