# Generated by Django 5.2.12 on 2026-04-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0004_alter_clearanceapproval_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceapproval',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
